name: Deploy to prod
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use deno version
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.2.0
      - name: Lint deno module
        run: deno fmt --check
      - name: Test deno module
        run: deno test --allow-net
  push_to_registry:
    needs: run_tests
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kohrongying/notes-backend/notes-backend
          tag_with_ref: true
  update_server_image:
    needs: push_to_registry
    name: Remote SSH to pull updated image
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.PROD_HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -aq)
            docker pull docker.pkg.github.com/kohrongying/notes-backend/notes-backend:latest
            docker run -d -p 80:8000 docker.pkg.github.com/kohrongying/notes-backend/notes-backend:latest