name: Publish Docker image (Master)
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kohrongying/notes-backend/notes-backend
          tag_with_ref: true
  update_server_image:
    name: Remote SSH to pull updated image
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.STAGING_HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            sudo docker pull docker.pkg.github.com/kohrongying/notes-backend/notes-backend:latest
            docker stop $(docker ps -aq)
            docker run -d -p 80:8000 docker.pkg.github.com/kohrongying/notes-backend/notes-backend:latest

